### PR TITLE
NoSuchSessionError : This driver instance does not have a valid session ID and may no longer be used.

### PR DESCRIPTION
**Pull request by okeul**
Hi !

In my project I have to launch two a11y tasks :
- a task for the components (included files) with specific rules (document-title false, html-has-lang false etc)
- a task for the pages with classic rules

But I have an error when I run these 2 tasks :
capture d ecran 2018-06-15 a 15 32 04

> NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

> From: Task: WebDriver.manage().setTimeouts({script: 60000})

I found the solution here : https://stackoverflow.com/questions/36828639/check-with-webdriver-if-browser-is-still-open#answer-36829763

It works like a charm :-)

### CODE REVIEW

**Comment by okeul** [comment]
It seems that there is still a problem. I will take a look

**Comment by okeul** [comment]
Ok it works now :-)

**Comment by okeul** [comment]
@felixzapata Do you need more information ?

**Comment by felixzapata** [comment]
@okeul hi, I will take a look ASAP. I've been off during a few days.

**Comment by felixzapata** [comment]
@okeul can you remove the extra spaces in the new code?

captura de pantalla 2018-06-19 a las 15 37 57

**Comment by felixzapata** [comment]
@okeul I've released version 2.1.2. Thanks for the pull request.

**Pull request merged**
