### PR TITLE
feat(errorOnViolation) Add a way to throw a plugin error on violations

### PR DESCRIPTION
**Pull request by SiTaggart**
Adding a way to throw an error on violation from axe. This is useful for CI environments if you want to break the build if any new violations are introduced.

I tried writing a test for it but found it super hard to detect an error being thrown correctly with assert. Any tips and I'll gladly provide one.

### CODE REVIEW

**Comment by felixzapata** [comment]
hi @SiTaggart, thanks for the pull request. I will take a look ASAP.

**Comment by felixzapata** [comment]
what kind of code did you use to detect the error with the assert?

**Comment by SiTaggart** [comment]
Something like this:

```
describe('using errorOnViolation', function () {
	it('should throw on a11y validation', function (done) {
		var options = {
			urls: [fixtures('broken.html')],
			errorOnViolation: true
		};

		var didError = false;

		try {
			axe(options, function () {
				done();
			})
		} catch (error) {
			didError = true;
			assertResult();
			done();
		}

		var assertResult = function() {
			assert.ok(didError);
		}
	});
});
```

But I have no idea what I'm doing

**Comment by SiTaggart** [comment]
Other tries 

```
describe('using errorOnViolation', function () {
		it('should throw on a11y validation', function (done) {
			var options = {
				urls: [fixtures('broken.html')],
				errorOnViolation: true
			};

			var didError = false;

			try {
				axe(options, function () {
					done();
				})
			} catch (error) {
				assert.equal(error.match(/Error: Encountered 1 axe violation errors/gi), null);
				done();
			}
		});
	});
```

```
describe('using errorOnViolation', function () {
		it('should throw on a11y validation', function (done) {
			var options = {
				urls: [fixtures('broken.html')],
				errorOnViolation: true
			};
			
			assert.throws(axe(options, function () {
				done();
			}), /Encountered1 axe/)
		});
	});
```

**Comment by rikki-iki** [comment]
Yes please!! Definitely need an option to make it exit a build when there are failures. I've tested this PR and it works well

**Comment by felixzapata** [comment]
@SiTaggart I will take a look to the code you pasted

**Comment by felixzapata** [comment]
@SiTaggart can you try this? It is not at the moment the best option but It is ok:

```
describe('using errorOnViolation', function () {
		it('should throw on a11y validation', function (done) {
			var options = {
				urls: [fixtures('broken.html')],
				errorOnViolation: true
			};
			return axe(options, done);
		});
	});
```
The problem is that [assert.throws is not going to work for exceptions that are raised asynchronously](https://stackoverflow.com/questions/26073873/assertionerror-missing-expected-exception-when-testing-async-requirejs-call-usi?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by SiTaggart** [comment]
Yeah, that doesn't work either. I've tried so many things so far, I just don't think it's possible to test with the way the plugin is written. Without it returning anything or a promise there's no way to handle the async error in tests.

**Comment by felixzapata** [comment]
@SiTaggart I will try to think a different approach with the plugin in order to allow a test for this case

**Comment by felixzapata** [comment]
work in progress:

captura de pantalla 2018-05-27 a las 11 31 56

**Comment by felixzapata** [comment]
hi @SiTaggart , can you take a look to this branch `SiTaggart-feat/error-on-violation-promises` to see if it's valid for your feature? The tests are updated and there is a new one related with your feature.

**Comment by SiTaggart** [comment]
Oh, that's so cool @felixzapata, I was so close. I was missing `return driver.quit();` in my attempt to return a promise. Code looks fine.

I tried to pull in your branch to our infra and it doesn't seem to be exiting correctly. 



That is a clean run, but it also doesn't show the error on a run with violations.

**Comment by felixzapata** [comment]
@SiTaggart how did you call the task?

**Comment by SiTaggart** [comment]
via an npm script so it runs the local version of gulp. `npm run gulp -- taskname`

**Comment by felixzapata** [comment]
I mean, the code of the task. Now with the promises, it changes a little how to use it because there is no `done` callback.

**Comment by rikki-iki** [comment]
That branch works for me! 

Removing the `done` callback from the gulp task, so it's essentially;

```
gulp.task('axe', function() {
  return axe({ urls: ['src/file2.html'], errorOnViolation: true });	
});
```

Setting `errorOnViolation` to true shows the results and exits immediately, setting it to false (or ommitting it) shows the results and finishes as usual.

It would be great to see a new release soon :)

**Comment by SiTaggart** [comment]
Sorry it took so long, I updated my code and this works perfectly now! Thanks for the update, look forward to the release

**Comment by felixzapata** [comment]
@SiTaggart @rikki-iki hi, i'm a little busy now. I will release a new version as soon as possible.

**Comment by felixzapata** [comment]
@SiTaggart @rikki-iki I've release the version 3.0.0 with the changes of the branch `SiTaggart-feat/error-on-violation-promises` based on this pull request. Thanks for your pull request @SiTaggart .

**Comment by davepoon** [comment]
@felixzapata Thank you so much for your quick reply and release! And thanks for the PR @SiTaggart

**Pull request closed without merging**
