### PR TITLE
Update axe-webdriverjs to the latest version

### PR DESCRIPTION
**Pull request by kaelig**
Update: fixed! ~~Pending fix of this issue: https://github.com/dequelabs/axe-webdriverjs/issues/23~~

# Change Log

### Added
- Support for axe-cli by passing in a source for axe-core version

### Changed
- Upgrade to Selenium 3, which requires Node 6
- Replace `~` with `^` in package.json to get more 
- Allow running with Selenium remotely in tests

~~Here's an open issue, please chime in if you'd like release notes in axe-webdriverjs!
https://github.com/dequelabs/axe-webdriverjs/issues/22~~ There is now a change log :)

### CODE REVIEW

**Comment by kaelig** [comment]
cc @SiTaggart

**Comment by felixzapata** [comment]
hi, I can´t merge this pull request until the new version being released.

**Comment by kaelig** [comment]
@felixzapata correct, I was a bit too eager :) Merging this PR is pending fix of this issue: dequelabs/axe-webdriverjs#23

**Comment by kaelig** [comment]
@felixzapata I updated the PR pointing to the latest version (0.5.0) that was released yesterday.

**Comment by felixzapata** [comment]
Hi @kaelig , happy holidays. Can you update the `package.json` file to bump the `selenium-webdriver` from `^2.53.3` to `^3.0.0`.

It is necessary in order to avoid this warn: `npm WARN axe-webdriverjs@0.5.0 requires a peer of selenium-webdriver@^3.0.0 but none was installed`

**Comment by kaelig** [comment]
@felixzapata done, happy holidays to you too!

**Comment by felixzapata** [comment]
hi @kaelig, I've released the version 1.4.0.

Thanks for your pull request.

**Comment by kaelig** [comment]
Thank you @felixzapata! v1.4.0 doesn't show up [in the npm registry](https://www.npmjs.com/package/gulp-axe-webdriver) yet, is this normal?

**Comment by felixzapata** [comment]
Hmmm.. it is not normal because a few hours ago I published without errors and now, I did it again and it says, again, no errors:

```
20:00 ~/$ npm publish ./
+ gulp-axe-webdriver@1.4.0
```
I don't know if there is some error in the npm registry

**Comment by kaelig** [comment]
Looks good now, thanks!

**Comment by felixzapata** [comment]
I don't know if is cache or what, but sometimes in the npm registry it shows the last version and other times it shows the previous version. I've checked it with [npm semver calculator](https://semver.npmjs.com/) and always shows the last version.

**Pull request merged**
